import Foundation

enum IconosEstandar: String, Codable, CaseIterable, Hashable {
    case alquiler = "ALQUILER"
    case hipoteca = "HIPOTECA"
    case agua = "AGUA"
    case gas = "GAS"
    case luz = "LUZ"
    case internet = "INTERNET"
    case supermercado = "SUPERMERCADO"
    case restaurantes = "RESTAURANTES"
    case cafeterias = "CAFETERIAS"
    case comidaRapida = "COMIDA_RAPIDA"
    case delivery = "DELIVERY"
    case combustible = "COMBUSTIBLE"
    case transportePublico = "TRANSPORTE_PUBLICO"
    case mantenimientoVehiculo = "MANTENIMIENTO_VEHICULO"
    case segurosVehiculo = "SEGUROS_VEHICULO"
    case medicina = "MEDICINA"
    case farmacia = "FARMACIA"
    case consultasMedicas = "CONSULTAS_MEDICAS"
    case seguroSalud = "SEGURO_SALUD"
    case cursos = "CURSOS"
    case colegios = "COLEGIOS"
    case universidad = "UNIVERSIDAD"
    case libros = "LIBROS"
    case materiales = "MATERIALES"
    case suscripcionesEducacion = "SUSCRIPCIONES_EDUCACION"
    case cine = "CINE"
    case teatro = "TEATRO"
    case eventos = "EVENTOS"
    case videojuegos = "VIDEOJUEGOS"
    case viajes = "VIAJES"
    case turismo = "TURISMO"
    case deportes = "DEPORTES"
    case gimnasio = "GIMNASIO"
    case vestimenta = "VESTIMENTA"
    case calzado = "CALZADO"
    case accesorios = "ACCESORIOS"
    case electrodomesticos = "ELECTRODOMESTICOS"
    case muebles = "MUEBLES"
    case decoracion = "DECORACION"
    case creditos = "CREDITOS"
    case deudas = "DEUDAS"
    case interesesBancarios = "INTERESES_BANCARIOS"
    case comisiones = "COMISIONES"
    case cuidadoMascotas = "CUIDADO_MASCOTAS"
    case otros = "OTROS"

    var nombreLegible: String {
        switch self {
        case .alquiler: "Alquiler"
        case .hipoteca: "Hipoteca"
        case .agua: "Agua"
        case .gas: "Gas"
        case .luz: "Luz"
        case .internet: "Internet"
        case .supermercado: "Supermercado"
        case .restaurantes: "Restaurantes"
        case .cafeterias: "Cafeterías"
        case .comidaRapida: "Comida Rápida"
        case .delivery: "Delivery"
        case .combustible: "Combustible"
        case .transportePublico: "Transporte Público"
        case .mantenimientoVehiculo: "Mantenimiento Vehículo"
        case .segurosVehiculo: "Seguros Vehículo"
        case .medicina: "Medicina"
        case .farmacia: "Farmacia"
        case .consultasMedicas: "Consultas Médicas"
        case .seguroSalud: "Seguro Salud"
        case .cursos: "Cursos"
        case .colegios: "Colegios"
        case .universidad: "Universidad"
        case .libros: "Libros"
        case .materiales: "Materiales"
        case .suscripcionesEducacion: "Suscripciones Educación"
        case .cine: "Cine"
        case .teatro: "Teatro"
        case .eventos: "Eventos"
        case .videojuegos: "Videojuegos"
        case .viajes: "Viajes"
        case .turismo: "Turismo"
        case .deportes: "Deportes"
        case .gimnasio: "Gimnasio"
        case .vestimenta: "Vestimenta"
        case .calzado: "Calzado"
        case .accesorios: "Accesorios"
        case .electrodomesticos: "Electrodomésticos"
        case .muebles: "Muebles"
        case .decoracion: "Decoración"
        case .creditos: "Créditos"
        case .deudas: "Deudas"
        case .interesesBancarios: "Intereses Bancarios"
        case .comisiones: "Comisiones"
        case .cuidadoMascotas: "Cuidado Mascotas"
        case .otros: "Otros"
        }
    }

    var sfSymbol: String {
        switch self {
        case .alquiler, .hipoteca: "house.fill"
        case .agua: "drop.fill"
        case .gas: "flame.fill"
        case .luz: "bolt.fill"
        case .internet: "wifi"
        case .supermercado: "cart.fill"
        case .restaurantes: "fork.knife"
        case .cafeterias: "cup.and.saucer.fill"
        case .comidaRapida: "takeoutbag.and.cup.and.straw.fill"
        case .delivery: "bicycle"
        case .combustible: "fuelpump.fill"
        case .transportePublico: "bus.fill"
        case .mantenimientoVehiculo: "wrench.and.screwdriver.fill"
        case .segurosVehiculo: "car.fill"
        case .medicina: "cross.case.fill"
        case .farmacia: "pills.fill"
        case .consultasMedicas: "stethoscope"
        case .seguroSalud: "heart.fill"
        case .cursos: "book.fill"
        case .colegios: "building.columns.fill"
        case .universidad: "graduationcap.fill"
        case .libros: "books.vertical.fill"
        case .materiales: "pencil.and.ruler.fill"
        case .suscripcionesEducacion: "newspaper.fill"
        case .cine: "film.fill"
        case .teatro: "theatermasks.fill"
        case .eventos: "ticket.fill"
        case .videojuegos: "gamecontroller.fill"
        case .viajes: "airplane"
        case .turismo: "map.fill"
        case .deportes: "sportscourt.fill"
        case .gimnasio: "dumbbell.fill"
        case .vestimenta: "tshirt.fill"
        case .calzado: "shoe.fill"
        case .accesorios: "bag.fill"
        case .electrodomesticos: "tv.fill"
        case .muebles: "chair.fill"
        case .decoracion: "paintpalette.fill"
        case .creditos: "banknote.fill"
        case .deudas: "doc.text.fill"
        case .interesesBancarios: "percent"
        case .comisiones: "dollarsign.circle.fill"
        case .cuidadoMascotas: "pawprint.fill"
        case .otros: "ellipsis.circle.fill"
        }
    }
}
